### PR TITLE
Z80::instructionIN_a_in shouldn't modify CPU flags

### PR DESCRIPTION
**Pull request by baraclese**
This fixes the broken title screen graphics in R-Type and Kujaku Ou. It does not however fix the broken save menu in Phantasy Star.

### CODE REVIEW

**Comment by baraclese** [comment]
Actually I can't reproduce the Phantasy Star error anymore at the moment with this fix while I was sure that it still occurred the first time I compiled it.

**Comment by byuu** [comment]
Bless you. Even zexall didn't catch this.

**Comment by byuu** [comment]
I can still reproduce the Phantasy Star save menu corruption in any case =(

**Comment by baraclese** [comment]
Hmm, I can't. Did you create a new save file yet? I wonder if it's timing related because I could only reproduce it once it seems.

**Pull request merged**
