### PR TITLE
Fix a typo spotted by Coverity in the m68k core

### PR DESCRIPTION
**Pull request by zgoldstein420**

### CODE REVIEW

**Comment by byuu** [comment]
It's an instruction encoding oddity in the M68K CPU.

Screenshot_2019-10-08_11-34-59
Screenshot_2019-10-08_11-35-16

I (supposedly) pass https://github.com/flamewing/68k-bcd-verifier, so I'm pretty sure I have these implemented right. (I don't have a compiled test ROM for the 68K BCD verifier, sadly.)

**Comment by zgoldstein420** [comment]
Ah, my apologies.

**Comment by byuu** [comment]
Actually, we should look into this a bit more. The address version uses from,with whereas the data version uses with,from. Something's not right ...

**Comment by byuu** [comment]
Okay I renamed the X/Y registers to S(ource)/T(arget), which should hopefully make it cleaner. Hopefully I didn't break things, heh. If anyone has a compiled copy of flamewing's BCD 68K stressor, that'd be most helpful.

**Pull request closed without merging**
