### PR TITLE
Cirrus ci links

### PR DESCRIPTION
**Pull request by Screwtapello**
This PR does two things:

 - it replaces the generic link to the Cirrus CI website (which shows all builds from all branches) with individual links to the official "download latest build artifact" URLs from [the docs](https://cirrus-ci.org/guide/writing-tasks/#artifacts-instruction) (see the "URLs to the latest artifacts" block at the bottom of that section).
- It adds a marker file to the Linux binary builds. Once this PR is created, Cirrus CI should kick off a test build. Once it's complete, we can try to download the "latest build artifact" URL described above, and see if it does actually mess up the download links described above.

If the downloaded artifact *does* include the marker, maybe we can try adding `?branch=master` to the URLs and see if that helps.

If it does help, I'll amend the PR to remove the marker file, and add that parameter to the various URLs.

If it doesn't help, I guess we'll have to find a different CI provider, although I'm not sure anybody else provides Mac builds for free.

### CODE REVIEW

**Comment by Screwtapello** [comment]
Turns out there was a third possibility: Cirrus CI just ignored the marker file entirely, I think because it was empty. I also noticed that the downloaded archive had lost the execute-permission bit on the binaries. Therefore, I've updated the build script (just for Linux so far) to manually zip the file, and store that as a single artefact, instead of archiving a bunch of files and letting Cirrus build a zip file on demand.

**Comment by Screwtapello** [comment]
OK, as of this comment:

- The latest commit on [the Cirrus CI higan builds page](https://cirrus-ci.com/github/byuu/higan) is for this PR
- [The Linux build task](https://cirrus-ci.com/task/5663528097153024) from that commit has completed, and the "higan-nightly" artifact collection contains one artifact, `higan-nightly.zip`
- That .zip file contains all the files we expect, including the branch marker file
- The relevant download link [in the README file on my fork](https://github.com/Screwtapello/higan/tree/cirrus-ci-links) produces a 404 error, (I hope) because this PR has not landed on the trunk yet.
- [A similar download link](https://api.cirrus-ci.com/v1/artifact/github/byuu/higan/linux-x86_64-binaries/higan-nightly/higan-nightly/GPLv3.txt) that refers to a file which *does* get built on master works fine.

I'm *pretty* sure this proves that the download links in the README on my fork are "master only" and cannot be corrupted by somebody just making a PR with a trojan. However, the FreeBSD build hasn't completed yet, and it's concievable that Cirrus CI doesn't update their "latest build" links until all the tasks in a build have completed, so I'll need to wait for that to be sure.

Assuming that works, remaining tasks include:

- Remove the `touch ...` command from the Linux build script.
- Update all the other build tasks to create the .zip manually. I'm pretty sure macOS will ship with the `zip` tool, and I've got it covered on Ubuntu, but we'll need to figure out how to install it on FreeBSD.
- Update all the other download links in the README to use the new URL.

**Comment by byuu** [comment]
FreeBSD also has a package named 'zip'. I wonder if there's a way we can restore the +x bit (this also breaks macOS binaries) before zipping, or if not, then after.

**Comment by Screwtapello** [comment]
I notice you've manually merged some of the changes from this PR to master, so I've rebased my changes on top of them.

Current state of the PR:

- One commit that adds a marker file, so that we can tell whether a given archive was built on this branch or on master. I intend to remove this branch before merging.
- One commit that changes `.cirrus.yml` to use a platform-native zip tool, one that understands platform-specific ideas like "executable permission bit", instead of letting Cirrus build archives dynamically on whatever cloud service they use.

Once this builds successfully, I'll verify that the updated links in the README still download builds from  the master branch, rather than this PR, remove the marker file instruction, and then it should be ready to go.

**Comment by Screwtapello** [comment]
My previous commit built successfully, and I verified that:

- Cirrus built the branch content successfully
- The "Nightly build" links I've put in the README only download from the master branch, not from PRs
- The downloaded archives contain all the files and directories higan needs, and have the executable bit set correctly on Linux, FreeBSD and macOS

I've removed the "extra marker file" commit from the branch, so I think this is ready to merge.

The one oddity I've found is that although the Linux binaries for `icarus` and `genius` boot up correctly, the Linux binary for `higan` immediately crashes with "Illegal instruction" on my Celeron Skylake laptop (this problem is [also reported for bsnes on reddit](https://www.reddit.com/r/emulation/comments/ciy5tj/bsnes_v108_released/evbbirm/) ). Poking around with GDB, apparently the illegal instruction is  `vpxor`,  and my laptop does not support AVX. It seems `higan/GNUmakefile` builds with `-march-native`, so the binaries are optimised for whatever crazy machine Cirrus CI chooses to run our builds. We might want to be a bit more deliberate about choosing a target architecture, but that's something we can safely decide later.

**Comment by byuu** [comment]
I've merged your changes and added a new local=false Makefile rule to disable -march=native, thank you so much!

**Pull request closed without merging**
